name: flexible_data_table
description: "This package supports server-side datatables, which can significantly enhance performance when dealing with large datasets by offloading data processing to the server. #Datatabel #ServerSideDatatable"
version: 1.1.1

#homepage: https://iTechQua.github.io
repository: https://github.com/iTechQua/flexible_data_table
issue_tracker: https://github.com/iTechQua/flexible_data_table/issues
funding:
  - https://www.github.com/sponsors/iTechQua

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: '>=0.0.1 <7.1.0'
  path_provider: '>=0.0.1 <7.1.0'
  pdf: '>=0.0.1 <7.1.0'
  universal_html: '>=0.0.1 <7.1.0'
  excel: '>=0.0.1 <7.1.0'
  permission_handler: '>=0.0.1 <13.1.0'
  share_plus: '>=0.0.1 <12.1.0'
  shared_preferences: '>=0.0.1 <12.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
